require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - lib/basketball/draft/cli.rb
    - tmp/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 35

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleMemoizedHelpers:
  Max: 10

Metrics/ParameterLists:
  Max: 6

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9
