require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - tmp/**/*
    - vendor/**/*

RSpec/MultipleMemoizedHelpers:
  Max: 30

RSpec/ExampleLength:
  Max: 25

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 2

Metrics/ParameterLists:
  Max: 6

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 25
